import { BillingReference } from './billing-reference-model';
import { DeliveryTerms } from './delivery-terms-model';
import { Price } from './price-model';
import { TaxTotal } from './tax-total-model';
import { AllowanceCharge } from './allowance-charge-model';
import { PaymentTerms } from './payment-terms-model';
import { Delivery } from './delivery-model';
import { Party } from './party-model';
import { DocumentReference } from './document-reference-model';
import { Period } from './period-model';
import { OrderLineReference } from './order-line-reference-model';
import { LineReference } from './line-reference-model';
import { Item } from './item-model';
import { PriceExtension } from './price-extension-model';
export class InvoiceLine {
    iD: string;
    uUID: string;
    note: string;
    invoicedQuantity: number;
    lineExtensionAmount: number;
    taxPointDate: Date;
    accountingCostCode: number;
    accountingCost: string;
    paymentPurposeCode: number;
    freeOfChargeIndicator: Indicator;
    invoicePeriod: Period;
    orderLineReference: OrderLineReference;
    despatchLineReference: LineReference;
    receiptLineReference: LineReference;
    billingReference: BillingReference;
    documentReference: DocumentReference;
    pricingReference: PricingReference;
    originatorParty: Party;
    delivery: Delivery;
    paymentTerms: PaymentTerms;
    allowanceCharge: AllowanceCharge;
    taxTotal: TaxTotal;
    withholdingTaxTotal: TaxTotal;
    item: Item;
    price: Price;
    deliveryTerms: DeliveryTerms;
    subInvoiceLine: InvoiceLine;
    itemPriceExtension: PriceExtension;
}